name: refreezer
description: ReFreezer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  app_links: ^6.0.1
  animations: ^2.0.10
  async: ^2.11.0
  audio_service: ^0.18.14
  audio_session: ^0.1.20
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3
  collection: ^1.18.0
  connectivity_plus: ^6.0.2
  country_currency_pickers: ^3.0.0
  crypto: ^3.0.3
  custom_navigator:
    path: ./custom_navigator
  device_info_plus: ^10.1.0
  #disk_space_plus: ^0.2.3
  # Gradle 8 updated version:
  disk_space_plus:
    git:
      url: https://github.com/famasf1/disk_space_plus.git
  draggable_scrollbar: ^0.1.0
  encrypt: ^5.0.3
  envied: ^0.5.3
  #equalizer_flutter: ^0.0.1
  # Gradle 8 updated version:
  equalizer_flutter:
    path: ./equalizer_flutter
  #external_path: ^1.0.3
  # Gradle 8 updated version:
  external_path:
    path: ./external_path
  filesize: ^2.0.1
  fluttericon: ^2.0.0
  fluttertoast: ^8.2.4
  flutter_cache_manager: ^3.3.1
  flutter_displaymode: ^0.6.0
  #flutter_file_dialog: ^3.0.1
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.0.0
  flutter_material_color_picker: ^1.2.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  html: ^0.15.3
  http: ^1.2.1
  i18n_extension: ^12.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  #just_audio:
  #  git:
  #    url: https://github.com/ryanheise/just_audio.git
  #    ref: visualizer
  #    path: just_audio
  #just_audio_platform_interface:
  #  git:
  #    url: https://github.com/ryanheise/just_audio.git
  #    ref: visualizer
  #    path: just_audio_platform_interface
  logging: ^1.2.0
  #marquee: ^2.2.3
  marquee:
    path: ./marquee
  #move_to_background: ^1.0.1
  # Gradle 8 updated version:
  move_to_background:
    path: ./move_to_background
  numberpicker: ^2.1.2
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.1
  #permission_handler: ^11.1.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pointycastle: ^3.7.4
  quick_actions: ^1.0.6
  #random_string: ^2.0.1
  #restart_app: ^1.2.1
  # Gradle 8 updated version:
  #restart_app:
  #  git:
  #    url: https://github.com/Argaros/restart_app.git
  rxdart: ^0.27.7
  scrobblenaut:
    path: ./scrobblenaut
  share_plus: ^9.0.0
  spotify: ^0.13.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.2
  #version: ^3.0.2 Added contents in source directly for compatibility
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.4

dependency_overrides:
  # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - lib/.env
    - assets/cover.jpg
    - assets/cover_thumb.jpg
    - assets/icon_legacy.png
    - assets/icon.png
    - assets/favorites_thumb.jpg
    - assets/browse_icon.png

  fonts:
    #    - family: Montserrat
    #      fonts:
    #        - asset: assets/fonts/Montserrat-Regular.ttf
    #        - asset: assets/fonts/Montserrat-Bold.ttf
    #          weight: 700
    #        - asset: assets/fonts/Montserrat-Italic.ttf
    #          style: italic
    - family: MabryPro
      fonts:
        - asset: assets/fonts/MabryPro.otf
        - asset: assets/fonts/MabryProItalic.otf
          style: italic
        - asset: assets/fonts/MabryProBold.otf
          weight: 700
        - asset: assets/fonts/MabryProBlack.otf
          weight: 900
    - family: ReFreezerIcons
      fonts:
        - asset: assets/fonts/ReFreezerIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
